### ISSUE TITLE
Link to datasets

### ISSUE THREAD

**Issue by aamir-s18** [opendatalab/OHR-Bench#1]
Hey, 

this is great work. I would like to download the dataset to evaluate some other techniques. Can you please make the data available thank you.

**Comment by Carkham** [comment]
Hi, thanks for your interests. We have released our datasets at [https://huggingface.co/datasets/opendatalab/OHR-Bench](https://huggingface.co/datasets/opendatalab/OHR-Bench). Enjoy it!

**Comment by aamir-s18** [comment]
Thank you!
